FROM zounds

EXPOSE 8000

RUN pip install pillow blosc falcon gunicorn redis

COPY remote/*.py remote/
COPY common/*.py common/

CMD gunicorn api:application \
    --bind 0.0.0.0:8000 --workers 2 --max-requests 100 --chdir remote/ \
    --log-level debug